[project]
name = "asr-training"
version = "0.1.0"
description = "ASR training recipes created for ivrit.ai"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
